### ISSUE TITLE
initializing ledger store: open migrates\\0-init-schema: file does not exist

### ISSUE THREAD

**Issue by ZinZingoo** [formancehq/ledger#311]
After i Download and Install the the pre-compiled binary "numary_x.y.z_Windows-64bit.zip",

I fellow the tutos :

numary config init

numary storage init

numary version

Version: 1.7.1
Date: 2022-08-02T10:37:19Z
Commit: 22b2d2c

numary server start --debug

ok

but when, i start testing

intro.num :
send [COIN 100] (
  source = @world
  destination = @centralbank
)

numary exec dunshire intro.num

i get :
time="2022-08-10T16:07:33+01:00" level=fatal msg=EOF 

in the client side :

numary exec quickstart example.num
time="2022-08-10T05:44:44+01:00" level=fatal msg=EOF

and this error in the server side:

time="2022-08-10T16:18:02+01:00" level=debug msg="QueryRowContext: SELECT ledger FROM ledgers WHERE ledger = ? [dunshire]"
time="2022-08-10T16:18:02+01:00" level=debug msg="ExecContext: INSERT INTO ledgers (ledger, addedAt) VALUES (?, ?) ON CONFLICT DO NOTHING [dunshire 2022-08-10 16:18:02.8947982 +0100 CET m=+7.719215001]"
time="2022-08-10T16:18:02+01:00" level=debug msg="Initialize store"
time="2022-08-10T16:18:02+01:00" level=info msg=Request ip=127.0.0.1 latency=2.3679ms method=POST path=/dunshire/script status=500 user_agent=Go-http-client/1.1
time="2022-08-10T16:18:02+01:00" level=error msg="initializing ledger store: open migrates\\0-init-schema: file does not exist"

ps: I use sqlite as Driver
...
server:
  http:
    basic_auth: ""
    bind_address: localhost:3068
storage:
  cache: true
  dir: c:/.numary/data
  driver: sqlite
  postgres:
    conn_string: postgresql://localhost/postgres
  sqlite:
    db_name: numary
ui:
  http:
    bind_address: localhost:3068
version: 1.7.1

**Comment by gfyrag** [comment]
@ZinZingoo Hello! Thks for the report.
The bug is on Windows version.
The PR which fix it is https://github.com/numary/ledger/pull/312
Will be reviewed and merged probably tomorrow.
