### ISSUE TITLE
Negative values for account balance

### ISSUE THREAD

**Issue by agallan** [formancehq/ledger#341]
**Is your feature request related to a problem? Please describe.**
About the fact that accounts can't have negative values, is it possible to overcome this in some way ?
(In the formance documentation: Accounts in Formance Ledger cannot go negative! (Except for the special @world account).)

**Comment by jdupas22** [comment]
Hey Agallan ! Yes it's possible to have account with negative values, there is a mapping system with some rules you can use to allow this, and soon you'll be able to do apply some rules 'per transaction' if you want to allow overdraft on some accounts ! I'll get back to you soon with the documentation about this :)

**Comment by edwardmp** [comment]
@jdupas22 we are interested in this too, do you have an example Numscript that shows how to allow overdrafting on a transaction level? Could not find it in the docs.

**Comment by jdupas22** [comment]
Hey Edward ! Sorry for the delay ! Yes of course ! 

```
send [USD/2 500] (
  source = @foo allowing overdraft up to [USD/2 100]
  destination = @world
)
```
