### ISSUE TITLE
Ledger creates a segment connection / client even when Segment is disabled.

### ISSUE THREAD

**Issue by irfn** [formancehq/ledger#352]
**Describe the bug**
Ledger is making a connection to segment even when Segment integration is disabled. I use Pi-Hole blocker and this results in an error log printed in the log.

**To Reproduce**
Block api.segment.io DNS resolution via some means like Pi-Hole etc.

**Expected behavior**
Since the integration is disabled, there should be no client created / connection attempted.

**Logs**
segment 2022/10/17 21:34:23 ERROR: sending request - Post "https://api.segment.io/v1/batch": dial tcp [::]:443: connect: connection refused
segment 2022/10/17 21:34:23 ERROR: sending request - Post "https://api.segment.io/v1/batch": dial tcp [::]:443: connect: connection refused
segment 2022/10/17 21:34:23 ERROR: sending request - Post "https://api.segment.io/v1/batch": dial tcp [::]:443: connect: connection refused

**Environment (please complete the following information):**
 - OS: Osx 12.5.1
 - Numary Version 
 Version: 1.7.4
 Date: 2022-09-02T12:29:05Z
 Commit: ceeef7f

**Additional context**
the problem goes away if I disable Pi-Hole blocking

**Comment by edwardmp** [comment]
Also seeing this same issue.

**Comment by edwardmp** [comment]
I discovered why this happens also have a temp fix.

Issue is that basically, you need to both disable telemetry & segment for this to work, per the condition here: https://github.com/formancehq/ledger/blob/9f71b05dc5ee00dae3d6bc961013b5b7dba1ad9f/cmd/internal/analytics.go#L43

Setting both these env vars will make it stop posting to segment (although there definitely needs to be an option to set them independently)
```
      NUMARY_SEGMENT_ENABLED: false
      NUMARY_TELEMETRY_ENABLED: false
```
