### ISSUE TITLE
Usage of a different stream

### ISSUE THREAD

**Issue by smiziara** [formancehq/ledger#355]
Hello everyone,

Here we use Nats Jetstream as our core streaming and messaging and we want to keep that.
What would be the best way or starting point for us to add support for nats into ledger?

Thanks!

**Comment by smiziara** [comment]
We have a http bridge here for nats so we can use the http publisher for now!

**Comment by altitude** [comment]
OK great! We use Watermill under the hood, I’ll check how it looks to expose NATS support with it :)
