### ISSUE TITLE
Allowing unbounded overdraft does not work correctly

### ISSUE THREAD

**Issue by edwardmp** [formancehq/ledger#379]
**Describe the bug**

`Allowing unbounded overdraft` doesn't appear to work., and Ledger logs show:
`Internal errors executing script: processing tx 0: balance.insufficient.EUR/2`

**To Reproduce**
```
curl -X "POST" "http://localhost:3068/ledger/script" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "plain": "send [EUR/2 10] (\\n    source = @somewhere allowing unbounded overdraft\\n\\n    destination = @world\\n)"
}'
```

**Expected behavior**

I expect that by putting `allowing unbounded overdraft` in the numscript, the account should be able to go negative.

**Environment:**

 - Numary Version v.1.8.0

**Comment by jdupas22** [comment]
Hey Edward ! We're currently reviewing the PR that should fix this problem :)
