### ISSUE TITLE
Ledger Container with latest version that is v1.19.1 does not work

### ISSUE THREAD

**Issue by ali-furkan** [formancehq/ledger#438]
I tried to build your ledger container with [`the docker-compose`](https://raw.githubusercontent.com/formancehq/ledger/main/docker-compose.yml) that you presented on my machine and cannot launch it due to being exited. Also, it did not return an error. However, It worked when I changed the versions of ledger and control services as [`42fec392f21e21b8f255cfc5509739acb4582ecf`](https://github.com/orgs/formancehq/packages/container/ledger/73574020?tag=42fec392f21e21b8f255cfc5509739acb4582ecf) instead of [`latest`](https://github.com/orgs/formancehq/packages/container/ledger/72981267?tag=v1.9.1). You can set "latest" version to the last released if it is a general issue

**Comment by jdupas22** [comment]
Hey Ali, thanks for pointing this out! We're going to take a look at it and see what we can do :)

**Comment by jdupas22** [comment]
Hey @ali-furkan, we can't reproduce this error on our side, can you give us more precision on what you're doing?
A list of things that could help us:

- OS & version
- Docker version
- Wether you're using docker-compose or docker compose
- the logs output of your containers
