### ISSUE TITLE
Broken installation link in README

### ISSUE THREAD

**Issue by bryanhuhta** [formancehq/ledger#494]
:wave:

In the README, under the the [Installation section](https://github.com/formancehq/ledger/blob/1a3534f1dd5b6b98a4860dae3fc1a2c7f4aee3f9/README.md#getting-started), there is a link to installing via brew, yum, etc which is broken: https://docs.formance.com/docs/installation-1

**Comment by RohithSml** [comment]
@bryanhuhta I have made the changes and added a pull request

**Comment by flemzord** [comment]
Thanks for your contribution @RohithSml
