### ISSUE TITLE
Revert transaction

### ISSUE THREAD

**Issue by altitude** [formancehq/ledger#52]
## Summary

We should be able to revert a transaction without having to build the reverse transaction

## Proposal

```
POST /:ledger/transactions/:txid/revert
```

## Expected behaviors

Given the transaction:
```json
{
  "txid": 0,
  "postings": [
    {
      "source": "world",
      "destination": "users:001",
      "amount": 100,
      "asset": "COIN"
    },
    {
      "source": "users:001",
      "destination": "payments:001",
      "amount": 100,
      "asset": "COIN"
    }
  ]
}
```

The revert endpoint should attempt to commit the exact reverse transaction:
```json
{
  "txid": 1,
  "postings": [
    {
      "source": "payments:001",
      "destination": "users:001",
      "amount": 100,
      "asset": "COIN"
    },
    {
      "source": "users:001",
      "destination": "world",
      "amount": 100,
      "asset": "COIN"
    }
  ]
}
```

**Comment by henry-jackson** [comment]
@altitude What do you think about adding a "Reverse" method to the Transaction struct in `core/transaction.go`. The method would reverse the order of the postings in the Transaction, and switch the source and destination strings on each posting.

Then when the endpoint is hit, we will query for transaction using the ID in the URL, reverse the transaction using that method, and then post the new transaction to the ledger.

**Comment by henry-jackson** [comment]
Another consideration is that we should mark that a Transaction has been reverted - do you think it would be better to do this with a new db column/field on the struct or as Metadata?
