### ISSUE TITLE
Ledger Golang SDK installation guide doesn't work

### ISSUE THREAD

**Issue by al-kimmel-serj** [formancehq/ledger#523]
Hi.

I try to install Ledger Golang SDK as described [here](https://github.com/formancehq/ledger/blob/716461d42b028769c16e3bb76ebdc856a8eacab6/pkg/client/README.md#sdk-installation), but I see:
```
$ go get github.com/formancehq/stack/ledger/client
go: module github.com/formancehq/stack@upgrade found (v1.10.14), but does not contain package github.com/formancehq/stack/ledger/client
```

My environment:

```
$ go version
go version go1.23.1 darwin/arm64
```

I use ledger running in my k8s cluster, not in Formance Platform.

Could you help to fix it?

**Comment by flemzord** [comment]
Hello 
Please use: https://github.com/formancehq/formance-sdk-go

**Comment by al-kimmel-serj** [comment]
I can't use https://github.com/formancehq/formance-sdk-go, because I use only Ledger and I don't use Formance Gateway. Formance SDK has hardcoded prefix `/api/ledger/v2` for Ledger API operations and I can't override it.

**Comment by gfyrag** [comment]
Hi @al-kimmel-serj !
There is an error in the module path. I will fix it.
But, keep in mind this sdk can change, it is used internally for integration tests and some methods/parameters can be changed without any warning.

**Comment by al-kimmel-serj** [comment]
Ok. Will keep it in mind. Thank you, @gfyrag.)

**Comment by gfyrag** [comment]
@al-kimmel-serj The fix is merged on main.
You can go get it again.

**Comment by al-kimmel-serj** [comment]
@gfyrag I see error when I run:
```
$ go get github.com/formancehq/ledger/pkg/client
go: github.com/formancehq/ledger/pkg/client@upgrade (v0.0.0-20241024085040-32d22503503f) requires github.com/formancehq/ledger/pkg/client@v0.0.0-20241024085040-32d22503503f: parsing go.mod:
	module declares its path as: github.com/formancehq/stack/ledger/client
	        but was required as: github.com/formancehq/ledger/pkg/client
```

**Comment by al-kimmel-serj** [comment]
Sorry. Now it works. Maybe problem was on my MacBook. Thank you.
